project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  site-url: "https://travel.volumen.ca"
  title: "travel"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
  back-to-top-navigation: true
  page-footer:
    left: 1999-2025 Travel
    right: |
      Built with <a href="https://quarto.org"> Quarto {{< version >}}</a>
format:
  html:
    theme: cosmo #default journal cosmo litera sketchy
    css: styles.css
date-format: full
editor: visual

